### ISSUE TITLE
[BUG] Exception when parsing configuration file with multiple string actions for the same event

### ISSUE THREAD

**Issue by denilsonsa** [xaviml/controllerx#205] opened 2020-12-21 07:22 UTC
# Bug report

## Description

The [configuration example](https://xaviml.github.io/controllerx/others/custom-controllers) shows we can call multiple services by passing a list of dictionaries to a certain event. Thus, I thought I could simplify my life by passing a list of strings (in order to change both brightness and colortemp at the same button press). However, this throws an exception.

## Additional information

* Devices involved:
  * Model: IKEA 1743 as LightController
* Integration: `zha`
* AppDaemon version: 0.3.2
* ControllerX version: 4.2.1
* HACS version (if installed from there): 1.8.0
* Home Assistant Core version: 0.118.4

## AppDaemon app configuration

```yaml
cx_remote_a_light:
  module: controllerx
  class: E1743Controller
  controller: 'cc:cc:cc:ff:fe:02:06:26'
  integration: zha
  light: light.closet_gu10
  mapping:
    'on': toggle
    'off': release
    'on$2': on_full_brightness
    'off$2': on_min_brightness
    'on$3':
      - on_full_brightness
      - on_full_color_temp
    'off$3':
      - on_min_brightness
      - on_min_color_temp
    move_with_on_off_0_83: hold_brightness_toggle
    move_1_83: hold_colortemp_toggle
```

## Logs

```text
2020-12-21 08:12:49.445957 WARNING cx_remote_a_light: ------------------------------------------------------------
2020-12-21 08:12:49.447391 WARNING cx_remote_a_light: Unexpected error in worker for App cx_remote_a_light:
2020-12-21 08:12:49.448862 WARNING cx_remote_a_light: Worker Ags: {}
2020-12-21 08:12:49.450108 WARNING cx_remote_a_light: ------------------------------------------------------------
2020-12-21 08:12:49.452502 WARNING cx_remote_a_light: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 148, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 117, in initialize
    await super().initialize()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 39, in initialize
    await super().initialize()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 408, in initialize
    await super().initialize()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 90, in initialize
    else self.parse_action_mapping(custom_mapping)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 196, in parse_action_mapping
    return {event: self.parse_action(action) for event, action in mapping.items()}
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 196, in <dictcomp>
    return {event: self.parse_action(action) for event, action in mapping.items()}
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 349, in parse_action
    service = act["service"].replace(".", "/")
TypeError: string indices must be integers
```

## Additional Context

I expected that to work. (Or at least have a good error message pointing to the mistake, but I understand it's not totally needed due to large amounts of INFO logging around it.)

Sure, I can rewrite that to a single service call to HA that will set both parameters at once; it's just a bit more verbose, and it forces me to repeat the entity id both in the service calls and in the controller configuration.

**Comment by xaviml** [comment] 2020-12-22 18:47
Hey @denilsonsa,

Thank you for opening this. You are not the first that raises this "bug". It was also reported in #173 by @regystro. This is as of now supposed to work like this. You can find the reason in the other issue, but rethinking it now, I believe that this can be implemented. The problem I thought of is that hold action cannot be called simultaneously, but if I could keep track of the type of action is being held, then I could implement this. I would need to test it out, but we could see unexpected behavior when calling a hold action twice.

I will close this issue and reopen #173 for this purpose.

Regards,
Xavi M.

**Closed by xaviml** 2020-12-22 18:47 UTC
Labels: bug
