### ISSUE TITLE
[QUESTION] E1810 Controller left/right click don't work

### ISSUE THREAD

**Issue by gafain** [xaviml/controllerx#507] opened 2022-06-06 17:56 UTC
# Question

Hello, 
the left/right click stop working.
In the log I get this message:
There is already an action executing for `arrow_right_click`. If you want a different behaviour change `mode` parameter, the default value is `single`.

The controller control a Shelly rgbw2 device.

Last month work fine.

## Additional information

- Devices involved:
  - Model: Ikea1810
 
- Integration: z2m
- AppDaemon version: 0.8.2
- ControllerX version: 4.8.0
- HACS version 1.25.5
- Home Assistant Core version: 2022.6.2

## AppDaemon app configuration

```yaml
livingroom_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.pul02_action
  integration: z2m
  light: light.striscia

## Logs

2022-06-06 19:52:48.168903 WARNING livingroom_controller: ------------------------------------------------------------
2022-06-06 19:52:48.169402 WARNING livingroom_controller: Unexpected error in worker for App livingroom_controller:
2022-06-06 19:52:48.169835 WARNING livingroom_controller: Worker Ags: {'id': '465c3f65f1a5407eb2db289009b97e96', 'name': 'livingroom_controller', 'objectid': 'abea830838b44bd290d2cd29b0771844', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0xffff9e17f220>>, 'attribute': 'state', 'entity': 'sensor.pul02_action', 'new_state': 'arrow_right_click', 'old_state': 'None', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2022-06-06 19:52:48.170177 WARNING livingroom_controller: ------------------------------------------------------------
2022-06-06 19:52:48.170962 WARNING livingroom_controller: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 826, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 319, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 393, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 431, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 449, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 56, in run
    await action(*args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 61, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 585, in click
    attribute = await self.get_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 517, in get_attribute
    raise ValueError(
ValueError: This light does not support xy_color or color_temp
2022-06-06 19:52:48.171377 WARNING livingroom_controller: ------------------------------------------------------------

## Additional Context

**Comment by xaviml** [comment] 2022-06-08 21:01
Hi @gafain ,

It seems that the error you are getting is about the light not supporting xy color or color temperature. However, I suppose that your light support the xy color. The problem is that Home Assistant detects that does not support color this is why the error is shown. If you want to skip the check and send the xy color anyway, you can try:

```yaml
livingroom_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.pul02_action
  integration: z2m
  light: light.striscia
  supported_color_modes: ["xy"]
```

With this you are overriding the "supported_color_modes" from the light since yours should be empty or not present. Consider that this might still fail or not work, but at least it will not give you the same error and we can explore further.

Regards,
Xavi M.

**Comment by xaviml** [comment] 2022-06-15 15:53
Closing ticket for now. Happy to reopen it again for further discussion.

**Closed by xaviml** 2022-06-15 15:53 UTC
Labels: question

**Comment by inertia666** [comment] 2022-10-25 06:44
I use this controller but the left/right click don't change the saturation. The events are fired in appdaemon but nothing happens to my lights.

`<html><body>


2022-10-25 08:42:21.051047 INFO studio_remote: 🏃 Running `Predefined (click_color_down)` now
--
2022-10-25 08:42:21.048673 INFO studio_remote: 🎮 Button event triggered: `arrow_left_click`
2022-10-25 08:42:20.480371 INFO studio_remote: 🏃 Running `Predefined (release)` now
2022-10-25 08:42:20.478007 INFO studio_remote: 🎮 Button event triggered: `arrow_right_release`
2022-10-25 08:42:18.204734 INFO studio_remote: 🏃 Running `Predefined (hold_color_up)` now
2022-10-25 08:42:18.201228 INFO studio_remote: 🎮 Button event triggered: `arrow_right_hold`
2022-10-25 08:42:17.689920 INFO studio_remote: 🏃 Running `Predefined (click_color_up)` now
2022-10-25 08:42:17.687344 INFO studio_remote: 🎮 Button event triggered: `arrow_right_click`
2022-10-25 08:42:17.393920 INFO studio_remote: 🏃 Running `Predefined (release)` now
2022-10-25 08:42:17.391449 INFO studio_remote: 🎮 Button event triggered: `arrow_right_release`


</body>
</html>`

Have tried with and without the colour mode.

`studio_remote:
  module: controllerx
  class: E1810Controller
  integration:
    name: z2m
    listen_to: mqtt
  controller: 5B_remote_studio
  light: light.studio_ceiling_lights`
