### ISSUE TITLE
IKEA blinds on deconz, controllerx won't stop up/down movement when first started

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#199] opened 2020-12-14 14:14 UTC
# Bug report

## Description

I have finally moved my IKEA blinds (2 Fyrtur and 1 Kadrilj) to deconz. I got them to connect properly by following an intricate procedure, but they seem stable now.
I have added my blind controller as well of course, and according to normal use, if I press up or down during it moving up and vice versa for down, it should stop the movement.
However, it either continues (moving up, press up, continues up) or changes direction (moving up, press down, it changes direction to down).

## Additional information

* Devices involved:
  * Model: IKEA E1766
  * Model: Fyrtur blind or Kadrilj blind
* Integration: deconz
* AppDaemon version: 0.3.2
* ControllerX version: 4.2.1
* HACS version: 1.8.0
* Home Assistant Core version: 0.118.5

## AppDaemon app configuration

```yaml
nathalie-cover:
  module: controllerx
  class: E1766CoverController
  controller: nathalie_cover_control
  integration: deconz
  cover: cover.window_covering_device_36
```

## Logs

```text
(optional) Add relevant AppDaemon / Home Assistant logs which could help tackle the problem.
```

## Additional Context
The IKEA hub makes it stop the current movement, but as the controllerx doesn't, I guess it's a hub/controllerx thing, rather than a function built in to the blind.

**Comment by xaviml** [comment] 2020-12-16 21:34
Hi @fribse,

Indeed, you are right. If the blinds are moving and you press either of the buttons, it should stop. This is done progamatically in ControllerX, so ControllerX needs to be able to read the state of the blind. So my first question is:

Does the state of `cover.window_covering_device_36` changes to `opening` and `closing` when moving?

Also, do you have this problem when the blind is moving? So when the blind is still and you press open or close, works as expected?

Regards,
Xavi M.

**Comment by fribse** [comment] 2020-12-21 07:44
The button's work as expected if the curtain is not moving.
But I don't see it changing to opening/closing, it does update the 'current_position', and when it's at the end, it changes to 'open' or 'closed'.
But I didn't see that when it was on the IKEA hub either.
I don't see any attribute like that in deconz showing up.

**Comment by xaviml** [comment] 2021-01-03 19:13
Hi @fribse,

Sorry for the delay in answering. ControllerX listens for the cover to change to `opening` and `closing` when the cover is opening and closing respectively. These are the official states for a cover entity when moving. You can find the states in [here](https://developers.home-assistant.io/docs/core/entity/cover/#states) and these are the values from [HA core](https://github.com/home-assistant/core/blob/1fc4284a29602168708036c69d8d9fdea25bbc65/homeassistant/const.py#L241):

```python
STATE_OPEN = "open"
STATE_OPENING = "opening"
STATE_CLOSED = "closed"
STATE_CLOSING = "closing"
```

I did an investigation on the deCONZ integration for covers and I found out that it does not report the opening and closing state. The deCONZ cover entity can be found [here](https://github.com/home-assistant/core/blob/1fc4284a29602168708036c69d8d9fdea25bbc65/homeassistant/components/deconz/cover.py#L54). It should implement the following methods: `is_opening` and `is_closing`. I see in deCONZ API documentation that it is not reporting the opening and closing state (see [here](https://dresden-elektronik.github.io/deconz-rest-doc/devices/ikea/kadrilj_roller_blind/#state-attributes)).

> it does update the 'current_position'
When you say this, you mean that it literally says `current_position` or that it shows the current position?

Regards,
Xavi M.

**Comment by fribse** [comment] 2021-01-08 09:24
Hi Xavi

I think that the blind itself doesn't report 'opening' and 'closing', as I didn't see that appear when I had it connected via the IKEA hub either, so if that doesn't report it, then the deconz can't either.
When it is moving I the position is changing continuesly, something like every 2-3 s.
Under 0102 Windows covering
![image](https://user-images.githubusercontent.com/13660621/103997165-09bb9080-519b-11eb-97f5-0aaf38072eae.png)
I see the 0x0008 Current Position Lift Percentage
![image](https://user-images.githubusercontent.com/13660621/103997089-f1e40c80-519a-11eb-9342-d9ed31825772.png)
changing as the curtain moves.
In Home Assistant the **current_position** is updated every 1-3 s as far as I can see it

![image](https://user-images.githubusercontent.com/13660621/103997598-98c8a880-519b-11eb-8269-a0c2c1ef1d80.png)

**Comment by xaviml** [comment] 2021-01-12 22:13
Hi @fribse,

The problem is that by looking at the state or the attributes ControllerX won't know if the blind is opening and closing. This is why it does not stop because the cover entity state does not change to `opening` or `closing`. This is more an issue how deCONZ integrates blinds than another thing. In general, all blinds should be reporting the `opening` and `closing` states.

However, what I would recommend you is to make use of the double click functionality, or the hold-release. If using the latter, there is nothing to change in your config, you can just hold to open/close and release when you want the cover to stop. Or you could use the multiple click functionality, so:

- 1 click up: open cover
- 2 clicks up: stop cover
- 1 click down: close cover
- 2 clicks up: stop cover
 
Or:

- 1 click up: open cover
- 2 clicks up: close cover
- 1 click down: stop cover

Config for the first option would be:
```yaml
nathalie-cover:
  module: controllerx
  class: E1766CoverController
  controller: nathalie_cover_control
  integration: deconz
  cover: cover.window_covering_device_36
  multiple_click_delay: 500 # this is the default, if you have problem with 2-click detection, you can make it bigger
  merge_mapping:
    1002: open
    1002$2: stop
    2002: close
    2002$2: stop
```

I hope that this helps :+1: Happy to help you out with the configuration, but I am afraid there is no much I can do from ControllerX to fix this.

Regards,
Xavi M.

**Closed by xaviml** 2021-01-12 22:13 UTC
Labels: bug

**Comment by htvekov** [comment] 2021-01-13 20:50
Hi' @xaviml & @fribse 

Just a curious question 😉
Wouldn't it be a better solution (for all blinds) so use Ikea's E1743 instead of the E1766 ?
I simply don't understand why the h*ll Ikea has come up with an identical remote (only front plate engravement is different AFAIK) for blinds and stripped the HOLD commands from it ?? 🤔

Ciao !

**Comment by xaviml** [comment] 2021-01-13 21:09
Hi @htvekov,

That is what I exactly thought when I saw the new E1766. However, I learned recently that it does support release action. So whenever you click or hold it sends the same command, and in case of holding it, when released it sends an stop command. You can see that now in the device page: https://xaviml.github.io/controllerx/controllers/E1766

However, I still agree that E1743 is much better than E1766, but if you use it for blinds, both have the same functionality.

Regards,
Xavi M.
