### ISSUE TITLE
[BUG] Controllerx goes into a loop and crashes HAS when I run an unrelated HA script

### ISSUE THREAD

**Issue by Zipties** [xaviml/controllerx#642] opened 2022-12-09 21:27 UTC
# Bug report

## Description

When my nightly HA script runs (that has nothing to do with this app) controllerx goes into a loop causing excessive CPU usage on the host. This has been happening for months but has gone mostly unnoticed due to it happening after we are asleep.

## Additional information

- Devices involved:
  -None
  - ...
- Integration: Choose from `z2m`
- AppDaemon version: [ 0.10 (community addon) ]
- ControllerX version: [ v4.24.0]
- HACS version (if installed from there): [ v1.27.2]
- Home Assistant Core version: [ v2022.11.5]

## AppDaemon app configuration

```
kitchen_dimmer:
  module: controllerx
  class: E1744LightController
  controller: zigbee2mqtt/kitchen_switch/action
  integration: mqtt
  light: light.kitchen_lights
  merge_mapping:
    "brightness_step_up":
      - service: input_boolean.turn_off
        target:
        entity_id: input_boolean.kitchen_motion_helper
      - service: tts.google_say
        data:
          entity_id: media_player.kitchen_display
          message: Motion Control Off
          cache: true    
    "brightness_step_down":
      - service: input_boolean.turn_on
        target:
        entity_id: input_boolean.kitchen_motion_helper
      - service: tts.google_say
        data:
          entity_id: media_player.kitchen_display
          message: Motion Control On
          cache: true              
party_media_control:
  module: controllerx
  class: E1744MediaPlayerController
  controller: zigbee2mqtt/media_button/action
  integration: mqtt
  media_player: media_player.dinner_time
  merge_mapping:
    "brightness_step_up":
      - service: script.spotify_play
    "brightness_step_down":
      - service: script.spotify_play_hits_party_group

Bedroom_Switch:
  module: controllerx
  class: E1810Controller
  controller: zigbee2mqtt/bedroom_switch/action
  integration: mqtt
  light: light.bedroom_lights
  merge_mapping:
    "toggle":
      - service: script.bedroom_switch

Livingroom_Remote:
  module: controllerx
  class: E1810Controller
  controller: zigbee2mqtt/Living_Room_Remote/action
  integration: mqtt
  light: light.living_room_lights

  ```
## Logs

```
2022-12-09 01:17:16.237519 WARNING AppDaemon: Excessive time spent in utility loop: 3105.0ms, 3104.0ms in check_app_updates(), 1.0ms in other
2022-12-09 01:17:19.375657 INFO HASS: Evaluating startup conditions
2022-12-09 01:17:19.500978 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-09 01:17:19.501546 INFO HASS: All startup conditions met
2022-12-09 01:17:21.330473 INFO AppDaemon: Processing restart for HASS
2022-12-09 01:17:21.331288 INFO AppDaemon: Terminating kitchen_dimmer
2022-12-09 01:17:21.334516 INFO AppDaemon: Terminating party_media_control
2022-12-09 01:17:21.339218 INFO AppDaemon: Terminating Bedroom_Switch
2022-12-09 01:17:21.341951 INFO AppDaemon: Terminating Livingroom_Remote
2022-12-09 01:17:21.343439 INFO AppDaemon: Initializing app kitchen_dimmer using class E1744LightController from module controllerx
2022-12-09 01:17:21.363649 INFO AppDaemon: Initializing app party_media_control using class E1744MediaPlayerController from module controllerx
2022-12-09 01:17:21.367239 INFO AppDaemon: Initializing app Bedroom_Switch using class E1810Controller from module controllerx
2022-12-09 01:17:21.370523 INFO AppDaemon: Initializing app Livingroom_Remote using class E1810Controller from module controllerx
2022-12-09 01:17:21.393643 INFO kitchen_dimmer: 🎮 ControllerX v4.24.0
2022-12-09 01:17:21.462911 INFO party_media_control: 🎮 ControllerX v4.24.0
2022-12-09 01:17:21.505961 INFO Bedroom_Switch: 🎮 ControllerX v4.24.0
2022-12-09 01:17:21.583401 INFO Livingroom_Remote: 🎮 ControllerX v4.24.0
2022-12-09 01:19:25.566009 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:20:01.451749 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:20:01.661788 WARNING HASS: Error getting services - retrying
Task exception was never retrieved
future: <Task finished name='Task-4883608' coro=<HassPlugin.run_hass_service_check() done, defined at /usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py:783> exception=ClientResponseError(RequestInfo(url=URL('http://supervisor/core/api/services'), method='GET', headers=<CIMultiDictProxy('Host': 'supervisor', 'Authorization': 'Bearer d2539faf401d2056e21448bb3c26a4f85e0f01e91cde188b63e15db97c3f34359cdc527fbc5a060006e97109667791f9124220749865344b', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.1')>, real_url=URL('http://supervisor/core/api/services')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '16', 'Date': 'Fri, 09 Dec 2022 00:19:52 GMT', 'Server': 'Python/3.10 aiohttp/3.8.3')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 792, in run_hass_service_check
    hass_services = await self.get_hass_services()
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 754, in get_hass_services
    r.raise_for_status()
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2022-12-09 01:20:37.442464 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:21:13.438409 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:21:49.442487 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:22:25.468007 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:01.444359 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:28.275618 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:33.291259 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:38.300620 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:43.522160 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:49.198587 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:23:56.734271 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:02.004847 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:07.857697 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:12.923607 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:18.945411 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:24.010304 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 01:24:30.080505 INFO HASS: Connected to Home Assistant 2022.11.5
2022-12-09 01:24:32.048927 INFO HASS: Evaluating startup conditions
2022-12-09 01:24:32.205537 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-09 01:24:32.206078 INFO HASS: All startup conditions met
2022-12-09 01:24:32.525507 INFO AppDaemon: Processing restart for HASS
2022-12-09 01:24:32.528485 INFO AppDaemon: Terminating kitchen_dimmer
2022-12-09 01:24:32.532122 INFO AppDaemon: Terminating party_media_control
2022-12-09 01:24:32.541259 INFO AppDaemon: Terminating Bedroom_Switch
2022-12-09 01:24:32.547000 INFO AppDaemon: Terminating Livingroom_Remote
2022-12-09 01:24:32.549314 INFO AppDaemon: Initializing app kitchen_dimmer using class E1744LightController from module controllerx
2022-12-09 01:24:32.581040 INFO AppDaemon: Initializing app party_media_control using class E1744MediaPlayerController from module controllerx
2022-12-09 01:24:32.584847 INFO AppDaemon: Initializing app Bedroom_Switch using class E1810Controller from module controllerx
2022-12-09 01:24:32.588441 INFO AppDaemon: Initializing app Livingroom_Remote using class E1810Controller from module controllerx
2022-12-09 01:24:32.634915 INFO kitchen_dimmer: 🎮 ControllerX v4.24.0
2022-12-09 01:24:32.749067 INFO party_media_control: 🎮 ControllerX v4.24.0
2022-12-09 01:24:32.812501 INFO Bedroom_Switch: 🎮 ControllerX v4.24.0
2022-12-09 01:24:32.898494 INFO Livingroom_Remote: 🎮 ControllerX v4.24.0
2022-12-09 01:24:33.030455 INFO HASS: Registering new service songpal/set_sound_setting
2022-12-09 01:24:36.730456 INFO HASS: Registering new service nodered/trigger
2022-12-09 12:00:01.401333 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:06.411316 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:11.420501 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:16.430421 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:21.440485 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:26.450796 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:31.459072 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:36.470226 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:41.767339 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:46.899101 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:52.700229 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:00:59.353617 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:01:04.921904 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:01:10.049942 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:01:15.141458 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:01:20.167212 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-09 12:01:25.361038 INFO HASS: Connected to Home Assistant 2022.11.5
2022-12-09 12:01:26.450876 INFO HASS: Evaluating startup conditions
2022-12-09 12:01:26.584615 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-09 12:01:26.585226 INFO HASS: All startup conditions met
2022-12-09 12:01:26.895422 INFO AppDaemon: Processing restart for HASS
2022-12-09 12:01:26.896212 INFO AppDaemon: Terminating kitchen_dimmer
2022-12-09 12:01:26.898334 INFO AppDaemon: Terminating party_media_control
2022-12-09 12:01:26.900113 INFO AppDaemon: Terminating Bedroom_Switch
2022-12-09 12:01:26.902157 INFO AppDaemon: Terminating Livingroom_Remote
2022-12-09 12:01:26.903637 INFO AppDaemon: Initializing app kitchen_dimmer using class E1744LightController from module controllerx
2022-12-09 12:01:26.913422 INFO AppDaemon: Initializing app party_media_control using class E1744MediaPlayerController from module controllerx
2022-12-09 12:01:26.917493 INFO AppDaemon: Initializing app Bedroom_Switch using class E1810Controller from module controllerx
2022-12-09 12:01:26.920705 INFO AppDaemon: Initializing app Livingroom_Remote using class E1810Controller from module controllerx
2022-12-09 12:01:26.928194 INFO kitchen_dimmer: 🎮 ControllerX v4.24.0
2022-12-09 12:01:26.975775 INFO party_media_control: 🎮 ControllerX v4.24.0
2022-12-09 12:01:27.019746 INFO Bedroom_Switch: 🎮 ControllerX v4.24.0
2022-12-09 12:01:27.096560 INFO Livingroom_Remote: 🎮 ControllerX v4.24.0
2022-12-09 12:01:27.196366 INFO HASS: Registering new service nodered/trigger
2022-12-09 12:01:27.234596 INFO HASS: Registering new service songpal/set_sound_setting
```

## Additional Context

Script that causes the loop

```
alias: Sleep Mode - On
sequence:
  - service: input_boolean.turn_off
    target:
      entity_id:
        - input_boolean.away
        - input_boolean.awake
        - input_boolean.evening
        - input_boolean.bedroom_motion_helper
    data: {}
  - service: lifx.set_state
    data:
      brightness: 1
      kelvin: 1500
      transition: 5
    target:
      area_id:
        - living_room
        - kitchen
        - diningroom
        - bedroom
        - entryway
        - hallway
        - upstairs
    enabled: true
  - service: scene.turn_on
    target:
      entity_id: scene.sleep
    data: {}
    enabled: false
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_bedroom
        - switch.adaptive_lighting_sleep_mode_dining
        - switch.adaptive_lighting_sleep_mode_kitchen
        - switch.adaptive_lighting_sleep_mode_living_spaces
        - switch.adaptive_lighting_sleep_mode_patio
        - switch.adaptive_lighting_sleep_mode_upstairs
        - switch.adaptive_lighting_sleep_mode_bathroom
  - service: light.turn_off
    data:
      transition: 7
    target:
      area_id:
        - hallway
        - living_room
        - upstairs
      entity_id:
        - light.patio_sconce
        - light.living_spaces
  - service: light.turn_on
    data:
      transition: 6
      brightness_pct: 3
    target:
      entity_id:
        - light.patio_lights
        - light.entry
        - light.dining_table
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.sleep
    data: {}
  - service: script.upstairs_climate_set
    data: {}
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: script.downstairs_climate_test
    data: {}
  - if:
      - condition: state
        entity_id: person.cory_simpson
        state: home
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.fluorescent_light_appliance_module
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 250
      - service: button.press
        data: {}
        target:
          entity_id: button.tower_power
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: button.press
        data: {}
        target:
          entity_id:
            - button.tower_speed
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 1
      - service: button.press
        data: {}
        target:
          entity_id: button.tower_speed
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - service: button.press
        data: {}
        target:
          entity_id: button.tower_oscilate
    enabled: true
mode: single
icon: mdi:power-sleep

```

Had to add extra cores to keep HA up during the CPU spikes

![CleanShot 2022-12-09 at 15 15 24](https://user-images.githubusercontent.com/11506166/206798789-e071e21b-68a0-4ad2-8649-de7313d41907.jpg)

**Comment by xaviml** [comment] 2022-12-31 11:17
Hi @Zipties ,

Sorry for the delay in response. Have you checked the following?
- Comment/remove the ControllerX configurations (leaving an empty `apps.yaml` file), and check if issue persists.
- Check which addon or service is making the CPU go high.
- Disable the script and check if the issue persists.
- Disable/Stop AppDaemon addon and check if issue persists.

Let me know of these experiments, so we can discard/rule out where the problem is coming from. It is difficult to debug this issue without running some experiments first, it could be that the issue is not coming from ControllerX, but from AppDaemon or HA. In any case, I am happy to help you out on this matter! :)

Regards,
Xavi M.

**Comment by Zipties** [comment] 2022-12-31 23:41
> Hi @Zipties ,
> 
> Sorry for the delay in response. Have you checked the following?
> 
> * Comment/remove the ControllerX configurations (leaving an empty `apps.yaml` file), and check if issue persists.
> * Check which addon or service is making the CPU go high.
> * Disable the script and check if the issue persists.
> * Disable/Stop AppDaemon addon and check if issue persists.
> 
> Let me know of these experiments, so we can discard/rule out where the problem is coming from. It is difficult to debug this issue without running some experiments first, it could be that the issue is not coming from ControllerX, but from AppDaemon or HA. In any case, I am happy to help you out on this matter! :)
> 
> Regards, Xavi M.

No worries, I ended up putting appdaemon in its own container and haven’t noticed any issues since

I do know that the process that was being reported as using excess CPU was appdaemon, and controllerx is the only app on it. 

I've been spinning containers out of HAOS anyway for this very reason; can't have some container freaking out and taking down the whole house of cards

**Comment by xaviml** [comment] 2023-01-01 11:51
Hi @Zipties ,

Thank you for reporting back. By seeing the logs I see that AppDaemon is the one connecting and disconnecting from HA, so it seems more of an AppDaemon problem. I will be closing this issue for now unless we have a way to reproduce the error.

Regards,
Xavi M.

**Closed by xaviml** 2023-01-01 11:51 UTC
Labels: bug
